### ISSUE TITLE
Unable to execute command "magepack bundle"

### ISSUE THREAD

**Issue by sandeep570** [magesuite/magepack-magento#13]
Hello Team,

I have started looking at this pack for bundling and performance improvement so I have installed the magepack and after executing the "magepack bundle" I am getting the below error
> magepack bundle
ℹ Using bundling config from "/var/www/html/localproject/magepack.config.js".                                                                                                                    
ℹ Creating bundles for "pub/static/frontend/Magento/luma/en_US".                                                                                                                                  
 ERROR  bundlingConfig.forEach is not a function                                                                                                                                                  
  at /home/user/.nvm/versions/node/v14.4.0/lib/node_modules/magepack/lib/bundle.js:34:24
  at Array.forEach (<anonymous>)

Magepack version = 2.8.0
Node version = v14.4.0
Magento 2.4.1 open source
![Screenshot from 2022-07-04 14-58-28](https://user-images.githubusercontent.com/45820900/177126505-e33a2099-1b10-4aaf-bbc3-210713e22b61.png)

Could you please help me out?? I really need this.

**Comment by krisdante** [comment]
It seems your config is empty or malformed. Please see https://github.com/magesuite/magepack. 
Please do not use issues for support tickets.
