### ISSUE TITLE
use preload instead of prefetch

### ISSUE THREAD

**Issue by onlinebizsoft** [magesuite/magepack-magento#14]
why do we use prefetch instead of preload?

I understand prefetch will only load JS when the CPU is idle while preload will transfer file from network first. So prefetch is not optimized to pagespeed, a better option might be "preload"+"async" ?

**Comment by krisdante** [comment]
#7

**Comment by onlinebizsoft** [comment]
@krisdante you close it too fast but I think you should use preload in this case and add JS bundle for other pages using "prefetch" on the same page. Not sure if you have tested with pagespeed and how you decided this.

**Comment by krisdante** [comment]
I closed it as a duplicate. If you have something to add to the thread - please read and extend previous discussion (even if it is closed)
