### ISSUE TITLE
Magento loading min.js file ?

### ISSUE THREAD

**Issue by adexos-dev** [magesuite/magepack-magento#2]
Hello

Is it normal that Magento is still charging the min.js file for the current the page ? 

![image](https://user-images.githubusercontent.com/43342273/79798596-87afe100-8359-11ea-92e9-02214c9664da.png)

If yes why ? 
If no, is it possible to remove it ? On other tests this min file take a long time to be executed.

Thanks.

**Comment by krzksz** [comment]
I'm not sure if I understand correctly but both `common` and page-type-specific (in your case `pdp` bundles are needed.

The first one consists of all the modules that are used on every type of page so it can be loaded once and cached when users are browsing through the store.

The latter contains modules that are specific for certain page (currently `cms`, `pdp`, `category` and `checkout`).

**Comment by adexos-dev** [comment]
Yes that's correct, i understand that.
But is 781...a7.min.js generated by magento needed too ?

**Comment by krzksz** [comment]
Yes, they contain all the synchronous scripts that are added to the page (mainly via `default_head_blocks`) like `require.js` for example.

**Comment by adexos-dev** [comment]
Ok, it's clear
thanks you for answers !
