### ISSUE TITLE
PHP 7.4/Magento 2.4

### ISSUE THREAD

**Issue by JosephLeedy** [magesuite/magepack-magento#3]
Is there a timeline for PHP 7.4 and Magento 2.4 support?

**Comment by jissereitsma** [comment]
Current requirements should be ok, even though the `requirements` are actually missing, which is another issue: https://github.com/magesuite/magepack-magento/blob/1.x/composer.json

I have tested this and confirmed to be working under Magento 2.4 and PHP 7.4.

**Comment by krisdante** [comment]
It just works ;)
