### ISSUE TITLE
Can't turn on Magepack magento setting

### ISSUE THREAD

**Issue by simnhg8** [magesuite/magepack-magento#9]
Using Magento 2.4.1, PHP 7.4

Installed Magepack and also Magepack Magento Module 1.1.4

Module is enabled, but the option to turn Magepack on is missing from Admin panel in Developer mode
Even trying to turn it on via CLI gives this error:

The "dev/js/enable_magepack_js_bundling" path doesn't exist. Verify and try again.

**Comment by Erfans** [comment]
Please check if module `creativestyle/magesuite-magepack` has been installed and run the command `setup:upgrade`.
This should solve the error.

**Comment by magnus-bmx** [comment]
php bin/magento module:enable MageSuite_Magepack
php bin/magento c:f

That should do it.
